# -*- coding: utf-8 -*-
"""blockchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19EAF0BdtlvROol57MaR2RYM3rVqCDllh
"""

#Voting Management System

import hashlib
import time

class Voter:
  def __init__(self,voter_id, name):
    self.voter_id = voter_id
    self.name = name
    self.has_voted=False

class Candidate:
  def __init__(self,candidate_id,name):
    self.candidate_id=candidate_id
    self.name=name

class Block:
    def __init__(self, index, transactions, previous_hash):
        self.index = index
        self.timestamp = time.time()
        self.transactions = transactions
        self.previous_hash = previous_hash
        self.hash = self.calculate_hash()

    def calculate_hash(self):
        block_string = str(self.index) + str(self.timestamp) + str(self.transactions) + str(self.previous_hash)
        return hashlib.sha256(block_string.encode()).hexdigest()

class Blockchain:
    def __init__(self):
        self.chain = [self.create_genesis_block()]

    def create_genesis_block(self):
        return Block(0, "Genesis Block", "0")

    def get_latest_block(self):
        return self.chain[-1]

    def add_block(self, transactions):
        new_block = Block(len(self.chain), transactions, self.get_latest_block().hash)
        self.chain.append(new_block)

    def print_chain(self):
        for block in self.chain:
            print(f"\nBlock {block.index}")
            print(f"Transactions: {block.transactions}")
            print(f"Hash: {block.hash}")
            print(f"Prev Hash: {block.previous_hash}")

voters = {}
candidates = {}
blockchain = Blockchain()

def add_candidate():
    cid = input("Enter candidate ID: ")
    if cid in candidates:
        print("Candidate already exists!")
        return
    name = input("Enter name: ")
    candidates[cid] = Candidate(cid, name)
    print("Candidate added!")

def add_voter():
    vid = input("Enter voter ID: ")
    if vid in voters:
        print("Voter already exists!")
        return
    name = input("Enter name: ")
    voters[vid] = Voter(vid, name)
    print("Voter added!")

def cast_vote():
    vid = input("Enter voter ID: ")
    if vid not in voters:
        print("Voter not found!")
        return

    voter = voters[vid]

    if voter.has_voted:
        print("Already voted!")
        return

    cid = input("Enter candidate ID: ")
    if cid not in candidates:
        print("Candidate not found!")
        return

    transaction = f"{voter.name} voted for {candidates[cid].name}"
    blockchain.add_block(transaction)

    voter.has_voted = True
    print("Vote recorded!")

def print_blockchain():
    blockchain.print_chain()

def validate_chain():
    for i in range(1, len(blockchain.chain)):
        current = blockchain.chain[i]
        prev = blockchain.chain[i - 1]

        if current.hash != current.calculate_hash():
            print("Chain is invalid!")
            return

        if current.previous_hash != prev.hash:
            print("Chain is broken!")
            return

    print("Blockchain is valid!")

def menu():
    while True:
        print("\n1. Add Candidate")
        print("2. Add Voter")
        print("3. Cast Vote")
        print("4. Print Blockchain")
        print("5. Validate Chain")
        print("6. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            add_candidate()
        elif choice == "2":
            add_voter()
        elif choice == "3":
            cast_vote()
        elif choice == "4":
            print_blockchain()
        elif choice == "5":
            validate_chain()
        elif choice == "6":
            break
        else:
            print("Invalid choice!")

menu()

